{
	"id": 66064760,
	"body": "\u003ca id=\"c3\"\u003e\u003c/a\u003eComment 3:\n\n\u003cpre\u003ethe error is reported at the last line of the package (so depends on the order in which\nyou specify the files).  the same thing happens for \n\npackage foo\n\nvar a int\n\nfunc f() {\n   a\n}\n\n// more stuff\n\nfor which 6g which reports \nnonam.go:12: a not used   (12 is last line of file)\n\nthe cause is that a single node in the AST of type ONAME occurs as a statement, but\nsince ONAME nodes are shared the linenumber is that from its definition, and tyepcheck\nwisely doesn't try to use it to set linenumbers for yyerror, which usually doesn't\nmatter because there is some enclosing structure that has a usable linenumber anyway.\u003c/pre\u003e",
	"user": {
		"login": "lvdlvd",
		"id": 9462795,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2012-03-14T14:47:30Z",
	"updated_at": "2014-12-08T10:17:10Z"
}
