{
	"id": 126222936,
	"number": 13922,
	"state": "closed",
	"title": "panic: time: missing Location in call to Date",
	"body": "I was experiencing this issue with Go 1.5.1 and I am still experiencing with Go 1.5.2\r\n\r\nThis is my code:\r\n```\r\n60  func DateAddDays(sqlDate string, days int) string {\r\n61     t, _ := time.Parse(\"2006-01-02\", sqlDate)\r\n62     res := t.AddDate(0, 0, days)\r\n63     return res.Format(SqlDateFormat)\r\n64   }\r\n```\r\n\r\nline 62 fires this panic:\r\n\r\n```\r\npanic: time: missing Location in call to Date\r\n\r\ngoroutine 48877 [running]:\r\ntime.Date(0x1, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\r\n\t/usr/local/go/src/time/time.go:1023 +0x91\r\ntime.Time.AddDate(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x7f2000000000, 0x0)\r\n\t/usr/local/go/src/time/time.go:658 +0x115\r\ntrenit/utils.DateAddDays(0xc82527bb00, 0x12, 0x1, 0x0, 0x0)\r\n\tmyscript.go:62 +0xac\r\n```\r\n\r\nthis function runs thousands of times, but the panic only happens very rarely, in the order of 1 every 10,000 times\r\n\r\nvery strange error!",
	"user": {
		"login": "dbaroncelli",
		"id": 5320104,
		"type": "User",
		"site_admin": false
	},
	"comments": 2,
	"closed_at": "2016-01-12T16:57:30Z",
	"created_at": "2016-01-12T16:53:45Z",
	"updated_at": "2016-01-12T17:27:19Z"
}
