{
	"id": 217227946,
	"body": "@griesemer Thanks for the reply. I would like to add that in my case the function was returning a struct called \"Stats\", which is just an aggregation of various stats and errors occurring during parsing of a very large file, so the function in no way belonged to Stats. (Quite the opposite.)  Anyway, it sounds like you are aware of the issue. Carry on. :-)",
	"user": {
		"login": "cgay",
		"id": 491829,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2016-05-05T18:02:49Z",
	"updated_at": "2016-05-05T18:02:49Z"
}
