{
	"id": 66056064,
	"body": "\u003ca id=\"c15\"\u003e\u003c/a\u003eComment 15:\n\n\u003cpre\u003eI had a quick stab, trying to debug / understand what is really happening, but I could\nonly see that once first exception started, runtime·sighandler is hit 3 times, while\ngoing into runtime·newstack couple times as well. I think that\n\nr-\u003eEip = (uintptr)runtime·sigpanic;\n\ncomplicates everything even more. Plus if you add a chance of exception raised inside\nexception handling code, then anything is possible.\n\nAlex\u003c/pre\u003e",
	"user": {
		"login": "alexbrainman",
		"id": 9796621,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2011-05-26T07:12:40Z",
	"updated_at": "2014-12-08T10:09:52Z"
}
