{
	"id": 66075202,
	"body": "\u003ca id=\"c1\"\u003e\u003c/a\u003eComment 1:\n\n\u003cpre\u003eHad another manifestation of what I think is the same bug in a test that was checking\nthat the expected number of goroutines existed at some point:\n\nng := runtime.NumGoroutine()\nif ng \u003e 5 {\n    panic(fmt.Sprintf(\"Test ended with %d running goroutines\", ng))\n}\n\nit died with the following. goroutine 0 looks suspect.\n\npanic: Test ended with 6 running goroutines\n\ngoroutine 5 [running]:\ntesting.funcÂ·004()\n\t/build/go/go/src/pkg/testing/testing.go:341 +0xbc\ntest.TestCleanShutdown(0xc200000240)\n\ttest_test.go:32 +0x1a1\ntesting.tRunner(0xc200000240, 0xbd85a0)\n\t/build/go/go/src/pkg/testing/testing.go:346 +0x85\ncreated by testing.RunTests\n\t/build/go/go/src/pkg/testing/testing.go:426 +0x86b\n\ngoroutine 1 [chan receive]:\ntesting.RunTests(0x9a0718, 0xbd85a0, 0x1, 0x1, 0x45f801, ...)\n\t/build/go/go/src/pkg/testing/testing.go:427 +0x88e\ntesting.Main(0x9a0718, 0xbd85a0, 0x1, 0x1, 0xbe3088, ...)\n\t/build/go/go/src/pkg/testing/testing.go:358 +0x8a\nmain.main()\n\ttest/_test/_testmain.go:43 +0x9a\n\ngoroutine 0 [syscall]:\n\ngoroutine 6 [syscall]:\nsyscall.Syscall6()\n\t/build/go/go/src/pkg/syscall/asm_linux_amd64.s:40 +0x5\nsyscall.EpollWait(0x9, 0xc2001980c0, 0xa, 0xa, 0xffffffffffffffff, ...)\n\t/build/go/go/src/pkg/syscall/zerrors_linux_amd64.go:1871 +0x95\nnet.(*pollster).WaitFD(0xc2001980b0, 0xc20015be40, 0x0, 0x0, 0x0, ...)\n\t/build/go/go/src/pkg/net/fd_linux.go:151 +0x127\nnet.(*pollServer).Run(0xc20015be40)\n\t/build/go/go/src/pkg/net/fd_unix.go:212 +0x10a\ncreated by net.newPollServer\n\t/build/go/go/src/pkg/net/newpollserver_unix.go:33 +0x2d5\u003c/pre\u003e",
	"user": {
		"login": "alberts",
		"id": 409689,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2013-02-25T07:39:42Z",
	"updated_at": "2014-12-08T10:26:01Z"
}
